# https://www.sqlite.org/pragma.html#pragma_cache_size
sqlite.cache_size=-262144

# https://www.sqlite.org/pragma.html#pragma_synchronous
sqlite.synchronous=OFF

sqlite.create_table=true
sqlite.mmap_size=1000000000